[package]
name = "atlas_vm"
version = "0.0.0"
edition = "2021"

[lib]
doctest = false

[dependencies]
serde = { version =  "1.0.217", features = ["derive"] }
time = { version = "0.3.37", features = ["formatting"] }
rand = "0.8.5"
